const quotes = [
	{
		quote: "True human goodness, in all its purity and freedom, can come to the fore only when its recipient has no power. Mankind's true moral test, its fundamental test (which is deeply buried from view), consists of its attitude towards those who are at its mercy: animals.", 
		source: "Milan Kundera, The Unbearable Lightness of Being"
	},

	{	
		quote: "Don't cry because it's over, smile because it happened.", 
		source: "Dr. Seuss"
	},

	{	
		quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", 
		source: "Albert Einstein"
	},

	{	quote: "A room without books is like a body without a soul." , 
		source: "Marcus Tullius Cicero"
	},

	{	
		quote: "Without music, life would be a mistake.", 
		source: "Friedrich Nietzsche, Twilight of the Idols"
	},

	{	quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", 
		source: "Ralph Waldo Emerson"
	},

];

function randomRGB() {
	return Math.floor(Math.random()*256);
}

function randomBackGroundColor() {
	return `rgb(${randomRGB()},${randomRGB()},${randomRGB()})`	
}

// selecting a random quote with all properties
function getRandomQuote () {
	var rQ = Math.floor(Math.random()*quotes.length);
	var qu = quotes[rQ]
	return qu;
};

// printing quote generated by getRandomQuote function
function printQuote () {
	let randomQuote = getRandomQuote();
	let col = randomBackGroundColor();

	const quoteBox = document.getElementById('quote-box'); //container
	const nodeQuote = document.querySelector('.quote'); // p tags for quote
	const nodeSource = document.querySelector('.source'); // p tags for source
	const button = document.querySelector('#loadQuote');
	
	//updating the p tags with new content
	nodeQuote.innerHTML = randomQuote.quote;
	nodeSource.innerHTML = randomQuote.source;
	quoteBox.appendChild(nodeQuote);
	quoteBox.appendChild(nodeSource);

	//changing background color with each click
	document.body.style.backgroundColor = col; 
	button.style.backgroundColor = col;
};

// when user clicks anywhere on the button, the "printQuote" function is called
document.getElementById('loadQuote').addEventListener("click", printQuote, false);
